<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin/resource-meta.css', 'ResourceMeta'));
$this->htmlElement('body')->appendAttribute('class', 'browse resource-meta');
?>

<?php echo $this->pageTitle($this->translate('Resource templates'), 1, $this->translate('Resource meta')); ?>

<div class="breadcrumbs">
    <?php echo $this->translate('Resource templates'); ?>
</div>

<?php if ($resourceTemplates): ?>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Meta names count'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceTemplates as $resourceTemplate): ?>
        <?php $owner = $resourceTemplate->owner(); ?>
        <tr>
            <td>
                <?php echo $this->hyperlink($resourceTemplate->label(), $this->url('admin/resource-meta-resource-template/id', ['action' => 'show', 'id' => $resourceTemplate->id()], true)); ?>
                <ul class="actions">
                    <?php if ($resourceTemplate->userIsAllowed('update')): ?>
                    <li><?php echo $this->hyperlink('', $this->url('admin/resource-meta-resource-template/id', ['action' => 'edit', 'id' => $resourceTemplate->id()], true), ['class' => 'o-icon-edit']); ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td><?php echo $owner ? $this->hyperlink($owner->name(), $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])) : $this->translate('[No owner]'); ?></td>
            <td><?php echo count($resourceTemplatesMetaNames[$resourceTemplate->id()]); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('No resource templates found.'); ?></p>
</div>
<?php endif; ?>
