<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin/resource-meta.css', 'ResourceMeta'));
$this->htmlElement('body')->appendAttribute('class', 'resource-meta');
$resourceTemplatePorperties = $resourceTemplate->getResourceTemplateProperties();
?>

<?php echo $this->pageTitle($this->translate('Properties'), 1, $this->translate('Resource meta'), $resourceTemplate->getLabel()); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formElement($form->get('form_csrf')); ?>

<div id="page-actions">
    <input type="submit" value="<?php echo $this->escapeHtml($this->translate('Submit')); ?>">
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Resource templates'), $this->url('admin/resource-meta-resource-template')); ?>
    <div class="separator"></div>
    <?php echo $this->hyperlink($this->translate('Properties'), $this->url(null, ['action' => 'show'], true)); ?>
    <div class="separator"></div>
    Edit
</div>

<?php if ($resourceTemplatePorperties): ?>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Property'); ?></th>
            <th><?php echo $this->translate('Meta names'); ?></th>
            <th><?php echo $this->translate('Alternate label'); ?></th>
            <th><?php echo $this->translate('Data types'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceTemplatePorperties as $resourceTemplateProperty): ?>
        <?php $property = $resourceTemplateProperty->getProperty(); ?>
        <tr>
            <td><?php echo sprintf('%s : %s', $property->getVocabulary()->getLabel(), sprintf('<strong>%s</strong>', $property->getLabel())); ?></td>
            <td>
                <?php
                $select->setName(sprintf('resource_template_meta_names[%s]', $resourceTemplateProperty->getId()));
                $select->setValue($resourceTemplateMetaNames[$resourceTemplateProperty->getId()] ?? null);
                echo $this->formElement($select);
                ?>
            </td>
            <td><?php echo $resourceTemplateProperty->getAlternateLabel(); ?></td>
            <td>
                <ul>
                    <?php foreach ($resourceTemplateProperty->getDataType() as $dataType): ?>
                    <li><?php echo $this->dataType()->getLabel($dataType); ?></li>
                    <?php endforeach; ?>
                </ul>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="no-resources">
    <p><?php echo $this->translate('No resource template properties found.'); ?></p>
</div>
<?php endif; ?>

<?php echo $this->form()->closeTag(); ?>
